addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-versioning" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-github" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.7.7")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.10.4")
