addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.6.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci" % "0.6.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-versioning" % "0.6.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-github" % "0.6.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.6.6")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
